name: Sayid.so
description: >
<<<<<<< HEAD
    Website Soomaliyeed, halkan waxaad kagala soconkartaa arima ku saabsan talo, waano, diini iyo danta umada afka Somaliga.
=======
    Sayid.so waa web site Somali halkan kagala soco macluumaad, talo, warbixin, iyo diini intaba.
    
>>>>>>> branch 'gh-pages' of https://github.com/sayidso/sayid.so.git
about: >
<<<<<<< HEAD
    Sayid.so coming soon
=======
   Welcome to sayid.so, coming soon. Kusoo dhawaada sayid.so, mar-dhaw ayaanu soo daawici doona.
    <hr>
>>>>>>> branch 'gh-pages' of https://github.com/sayidso/sayid.so.git

master_repo: false
<<<<<<< HEAD
url: "sayidso.github.io/sayid.so"
=======
url: "https://sayid.so"
>>>>>>> branch 'gh-pages' of https://github.com/sayidso/sayid.so.git
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist']

paginate: 3

logo:             logo.png
disqus_shortname:

owner:
  name:           sayid.so
  avatar:         ""
  email:          ""
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  github:
  stackexchange:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-83638578-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
